class ShoppingCartPageObjects{

    constructor() {
        this.couponCodeTextBox = "(//input[@class='form-control'])[2]"
        this.couponCodeApplyButton = "//button[contains(text(),'Apply')]"
        this.verifyCouponCodeSuccessMessagePopUP = "//div[@class='Toastify__toast-body']"
        this.verifySuccessCouponMessage = "//small[@class='text-dark '] "
        this.verifyInvalidCouponCodeErrorMessage = "//div[@class='Toastify__toast-body']"
        this.verifyEmptyCouponCodeErrorMessage = "//div[@class='error-msg p-0 half-rem-mt']"
        this.verifyTotalPrice = "//div[@class='price']/child::span[@class='new-price']"
        this.productImage = "(//div[@class=' mt-2 img-container']/child::picture/child::img)"
        this.productName = "//div[@class='product-name']"
        this.productBrandName = "//small[@class='medium-grey']"
        this.productDiscountedPriceDetail = "//span[@class='price discount price']"
        this.productActualPriceDetail = "//div[@class='price ']"
        this.cartProductCount = "//span[@class='count d-inline-block bold align-middle']"
        this.productWeight = "//small[@class='d-block medium-grey weight-category']"
        this.deleteProductFromCart = "//button[@class='btn update-count-btn align-middle delBtn']"
        this.emptyCartImage = "//div[@class='empty-cart-holder']/child::img"
        this.removeAppliedCoupon = "//button[@class='btn btn-sm remove-promo']"
        this.mobileNumberBox = "//input[@class = 'form-control phone-number']"
        this.getVerificationCodeButton = "//button[text() = 'Get Verification Code via Text']"
        this.disabledResendverificationCodeButton = "//button[contains(text(),'Resend Verification Code')]"
        this.verificationCodeBox = "//input[@class = 'form-control otp-field']"
        this.loginVerificationSuccessMessage = "//div[text() = 'Verification successful']"
        this.cartUpdateSuccessMessage = "//div[text() = 'Cart updated successfully']"
        this.userNameBox = "//input[@class='form-control undefined'][@name='name']"
        this.debitCardRadioButton = "//input[@id='custom-radio2']"
        this.debitcardNumber = "//input[@name='cardNumber']"
        this.expiryDate = "//input[@name='cardExp']"
        this.cvvNumber = "//input[@name='cardCVV']"
        this.cardHolderName = "//input[@name='cardName']"
        this.deliveryTime = "//select[@class='form-control country-code time-dropdown']"
        this.tip$5ToDriver = "//button[text()='$5']"
        this.billingZipCodeBox = "//input[@name='zipcode']"
        this.userEmailBox = "//input[@name='email']"
        this.deliveryAddressTextArea = "//textarea[@class='form-control ']"
        this.zipCode = "//label[text()='Zipcode']/following-sibling::div/child::input"
        this.verifyTipToDriver = "//button[@class='btn tipAmount is-active']"
        this.verifySubtotal = "//div[text()='Subtotal']/following-sibling::div"
        this.verifyBundleDiscount = "//div[text()='Bundle Discount']/following-sibling::div"
        this.verifyNetSubtotal = "//div[text()='Net Subtotal']/following-sibling::div"
        this.verifyTotalTaxes = "//span[(contains(text(),'Total Taxes & Fees'))]/parent::div/following-sibling::div/child::span[2]"
        this.verifyHealthIssurance = "//div[contains(text(),'Health Insurance/Living Wages @3.5%  ')]/following-sibling::div"
        this.verifyDebitCardFee = "//div[text()='Debit Card Transaction Fee']/following-sibling::div"
        this.verifyStateCannabisTax = "//div[text()='State Cannabis Excise Tax @15%']/following-sibling::div"
        this.verifylocalCannabisBusinessTax = "//div[text()='Local Cannabis Business Tax @5%']/following-sibling::div"
        this.verifylocalSalesTax = "//div[text()='Local Sales Tax @9.5%']/following-sibling::div"
        this.verifyTotalFee = "//div[text()='Total (All Fees Included)']/following-sibling::div"
        this.verifyTip = "//span[text()='Tip']/parent::div/following-sibling::div"
        this.verifyTotalAmount = "//span[contains(text(),'Total Amount Payable')]/parent::div/following-sibling::div"
        this.bringItButton = "//button[text()='Bring It']"
        
    }
}

const shoppingCartPageObject = new ShoppingCartPageObjects()
export default shoppingCartPageObject